Update tests for files

diff --git a/.github/workflows/pipeline-test.yml b/.github/workflows/pipeline-test.yml
--- a/.github/workflows/pipeline-test.yml
+++ b/.github/workflows/pipeline-test.yml
@@ -5,7 +5,7 @@ name: Test Model Pipeline Inference
 
 on: [ pull_request ]
 jobs:
-  build:
+  pipeline:
     timeout-minutes: 10
     runs-on: ubuntu-latest
     defaults:
@@ -22,9 +22,33 @@ jobs:
         shell: bash
         run: |
           chmod +x pipeline.sh
-          ./pipeline.sh
+          ./pipeline.sh cache
 
-      - name: Get Docker Logs on Fail
+      - name: Check Dataset exists and is not empty
+        if: always()
+        working-directory: src/datasets/
+        run: |
+          dataset=*.csv
+          [ -f "$dataset" ] || { echo "Dataset file not found"; exit 1; }
+          [ -s "$dataset" ] || { echo "Dataset file is empty"; exit 1; }
+
+      - name: Check Pipeline Cache exists and is not empty
+        if: always()
+        working-directory: src/.pipeline_cache/
+        run: |
+          pipeline_cache=cache.csv
+          [ -f "$pipeline_cache" ] || { echo "Pipeline Cache file not found"; exit 1; }
+          [ -s "$pipeline_cache" ] || { echo "Pipeline Cache file is empty"; exit 1; }
+
+      - name: Check Dist exists and is not empty
+        if: always()
+        working-directory: src/dist/
+        run: |
+          dist=*.tar.gz2
+          [ -f "$dist" ] || { echo "Dist file not found"; exit 1; }
+          [ -s "$dist" ] || { echo "Dist file is empty"; exit 1; }
+
+      - name: Preprocess Docker Logs
         working-directory: src/
         if: always()
         run: |
@@ -35,34 +59,6 @@ jobs:
             --env-file preprocess/osu-data-docker/.env \
             logs $SVC > ${SVC}.log
           done
-#
-#      - name: Check Pipeline Cache
-#        working-directory: src/.pipeline_cache
-#        run: |
-#          [ -f cache.env ] || { echo "Cache file not found"; exit 1; }
-#          cat cache.env >> $GITHUB_ENV
-#
-#      - name: Check all env variables are set
-#        run: |
-#          : "${PIPELINE_RUN_CACHE:?PIPELINE_RUN_CACHE not set}"
-#          : "${DB_URL:?DB_URL not set}"
-#          : "${FILES_URL:?FILES_URL not set}"
-#          : "${FILES_DIR:?FILES_DIR not set}"
-#          : "${MODEL_NAME:?MODEL_NAME not set}"
-#          : "${DATASET_NAME:?DATASET_NAME not set}"
-#          : "${DB_NAME:?DB_NAME not set}"
-#          : "${DB_USERNAME:?DB_USERNAME not set}"
-#          : "${DB_PASSWORD:?DB_PASSWORD not set}"
-#          : "${DB_HOST:?DB_HOST not set}"
-#          : "${DB_PORT:?DB_PORT not set}"
-#          : "${SR_MIN:?SR_MIN not set}"
-#          : "${SR_MAX:?SR_MAX not set}"
-#          : "${ACC_MIN:?ACC_MIN not set}"
-#          : "${ACC_MAX:?ACC_MAX not set}"
-#          : "${MIN_SCORES_PER_MID:?MIN_SCORES_PER_MID not set}"
-#          : "${MIN_SCORES_PER_UID:?MIN_SCORES_PER_UID not set}"
-#          : "${MAX_SVNESS:?MAX_SVNESS not set}"
-#          : "${MODEL_PATH:?MODEL_PATH not set}"
 
       - name: Export src as Artifact
         if: always()
